name: app_login
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider : ^6.0.1
  get_it: ^7.2.0
  http: ^1.2.1
  flutter_secure_storage: ^4.2.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true